// Code generated by "stringer -type=EventStatus"; DO NOT EDIT.

package consts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pending-0]
	_ = x[Executing-1]
	_ = x[Complete-2]
	_ = x[Failed-3]
}

const _EventStatus_name = "PendingExecutingCompleteFailed"

var _EventStatus_index = [...]uint8{0, 7, 16, 24, 30}

func (i EventStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EventStatus_index)-1 {
		return "EventStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventStatus_name[_EventStatus_index[idx]:_EventStatus_index[idx+1]]
}
