// Code generated by "stringer -type=KeyAction"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Back-0]
	_ = x[Select-1]
	_ = x[Up-2]
	_ = x[Down-3]
	_ = x[Scout-4]
	_ = x[Colonize-5]
	_ = x[Search-6]
	_ = x[InsertText-7]
	_ = x[Quit-8]
}

const _KeyAction_name = "BackSelectUpDownScoutColonizeSearchInsertTextQuit"

var _KeyAction_index = [...]uint8{0, 4, 10, 12, 16, 21, 29, 35, 45, 49}

func (i KeyAction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_KeyAction_index)-1 {
		return "KeyAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyAction_name[_KeyAction_index[idx]:_KeyAction_index[idx+1]]
}
