// Code generated by "stringer -type=OrderType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreateColonyOrder-0]
	_ = x[SendFoodOrder-1]
	_ = x[SendMineralOrder-2]
	_ = x[SendEnergyOrder-3]
}

const _OrderType_name = "CreateColonyOrderSendFoodOrderSendMineralOrderSendEnergyOrder"

var _OrderType_index = [...]uint8{0, 17, 30, 46, 61}

func (i OrderType) String() string {
	if i < 0 || i >= OrderType(len(_OrderType_index)-1) {
		return "OrderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderType_name[_OrderType_index[i]:_OrderType_index[i+1]]
}
